apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: self-service-backend
  namespace: self-service
  labels:
    app: self-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: self-service-backend
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
